!obj:pylearn2.train.Train {
    dataset: &train !obj:load_data.load_supervised {
        minyear: 1950,
        maxyear: 1985,
        lt: %2.4f,
        ln: %2.4f,
        batchsize: 365,
        which: train
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 365,
        layers: [
                 !obj:pylearn2.models.mlp.PretrainedLayer {
                     layer_name: 'h1',
                     layer_content: !pkl: "models/grbm_l1_%i.pkl"
                 },
                 !obj:pylearn2.models.mlp.PretrainedLayer {
                     layer_name: 'h2',
                     layer_content: !pkl: "models/rbm_l2_%i_%i.pkl"
                 },
                !obj:pylearn2.models.mlp.PretrainedLayer {
                     layer_name: 'h3',
                    layer_content: !pkl: "models/rbm_l3_%i_%i.pkl"
                 },
                 !obj:pylearn2.models.mlp.LinearGaussian {   ## this will be changed to an SVR
                     init_bias: !obj:pylearn2.models.mlp.mean_of_targets {
                       dataset: *train },
                     init_beta: !obj:pylearn2.models.mlp.beta_from_targets {
                       dataset: *train },
                     min_beta: 1.,
                     max_beta: 50.,
                     beta_lr_scale: 1.,
                     dim: 1,
                     # max_col_norm: 1.9365,
                     layer_name: 'y',
                     irange: .005
                 }
                ],
        nvis: 2178
    },
       algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
                learning_rate: 0.005,
                batch_size: 365,
                monitoring_batches: 10,
                monitoring_dataset : {
                        'train' : *train,
                        'test' : !obj:load_data.load_supervised {
                            minyear: 1986,
                            maxyear: 1999,
                            lt: %2.4f,
                            ln: %2.4f,
                            batchsize: 365,
                            which: 'test'
                         },
                },
                termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
                          max_epochs: 1000,
                },
        },
    extensions: [

            # This callback makes the momentum grow to 0.9 linearly. It starts
            # growing at epoch 5 and finishes growing at epoch 6.
            # !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
             #   final_momentum: .9,
             #   start: 5,
             #   saturate: 6
           # },
    ],
    save_path: "/scratch/vandal.t/mlp_%2.2f_%2.2f.pkl",
    save_freq: 100
}
